In [74]:
import numpy as np
import pandas as pd

from sklearn.model_selection import KFold, cross_val_score
from sklearn.linear_model import LinearRegression,Ridge
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, StandardScaler, OrdinalEncoder
from sklearn.compose import ColumnTransformer

from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error

from sklearn.decomposition import PCA

In [75]:
df = pd.read_csv('gurgaon_properties_feature_selectionV2.csv').drop(columns=['store room','floor_category','balcony'])

In [76]:
df.head()

  property_type      sector  price  bedRoom  ...  built_up_area servant room  furnishing_type  luxury_category
0         house   sector 11   4.00        5  ...         2025.0            0                1              Low
1          flat  sector 110   3.30        4  ...         3032.0            1                1           Medium
2          flat  sector 104   2.30        3  ...         2217.0            1                1           Medium
3         house   sector 50   3.99        4  ...         4500.0            1                0           Medium
4          flat   sector 37   1.45        3  ...         1711.0            0                1           Medium

[5 rows x 10 columns]

In [77]:
# 0 -> unfurnished
# 1 -> semifurnished
# 2 -> furnished

In [78]:
# Numerical = bedRoom, bathroom, built_up_area, servant room
# Ordinal = property_type, furnishing_type, luxury_category 
# OHE = sector, agePossession

In [79]:
df['agePossession'] = df['agePossession'].replace(
    {
        'Relatively New':'new',
        'Moderately Old':'old',
        'New Property' : 'new',
        'Old Property' : 'old',
        'Under Construction' : 'under construction'
    }
)

In [80]:
df.head()

  property_type      sector  price  bedRoom  ...  built_up_area servant room  furnishing_type  luxury_category
0         house   sector 11   4.00        5  ...         2025.0            0                1              Low
1          flat  sector 110   3.30        4  ...         3032.0            1                1           Medium
2          flat  sector 104   2.30        3  ...         2217.0            1                1           Medium
3         house   sector 50   3.99        4  ...         4500.0            1                0           Medium
4          flat   sector 37   1.45        3  ...         1711.0            0                1           Medium

[5 rows x 10 columns]

In [81]:
df['property_type'] = df['property_type'].replace({'flat':0,'house':1})

C:\Users\kushs\AppData\Local\Temp\ipykernel_45620\71934247.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['property_type'] = df['property_type'].replace({'flat':0,'house':1})

In [82]:
df.head()

   property_type      sector  price  bedRoom  ...  built_up_area servant room  furnishing_type  luxury_category
0              1   sector 11   4.00        5  ...         2025.0            0                1              Low
1              0  sector 110   3.30        4  ...         3032.0            1                1           Medium
2              0  sector 104   2.30        3  ...         2217.0            1                1           Medium
3              1   sector 50   3.99        4  ...         4500.0            1                0           Medium
4              0   sector 37   1.45        3  ...         1711.0            0                1           Medium

[5 rows x 10 columns]

In [83]:
df['luxury_category'] = df['luxury_category'].replace({'Low':0,'Medium':1,'High':2})

C:\Users\kushs\AppData\Local\Temp\ipykernel_45620\2576796079.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['luxury_category'] = df['luxury_category'].replace({'Low':0,'Medium':1,'High':2})

In [84]:
new_df = pd.get_dummies(df,columns=['sector','agePossession'],drop_first=True,dtype=int)

In [85]:
new_df

      property_type  price  bedRoom  ...  sector_sohna  agePossession_old  agePossession_under construction
0                 1   4.00        5  ...             0                  1                                 0
1                 0   3.30        4  ...             0                  0                                 0
2                 0   2.30        3  ...             0                  1                                 0
3                 1   3.99        4  ...             0                  0                                 0
4                 0   1.45        3  ...             0                  0                                 0
...             ...    ...      ...  ...           ...                ...                               ...
3619              0   1.40        3  ...             0                  0                                 0
3620              0   1.00        3  ...             0                  0                                 0
3621              0   0.79        4  ...             0                  0                                 0
3622              0   0.60        2  ...             0                  0                                 0
3623              0   0.65        2  ...             0                  0                                 0

[3624 rows x 105 columns]

In [86]:
X = new_df.drop(columns=['price'])
y = new_df['price']

In [87]:
y_log = np.log1p(y)

In [88]:
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

In [89]:
X_scaled = pd.DataFrame(X_scaled,columns=X.columns)

In [90]:
X_scaled

      property_type   bedRoom  bathroom  ...  sector_sohna  agePossession_old  agePossession_under construction
0          1.900181  1.530684  0.503752  ...     -0.209234           1.625488                         -0.292156
1         -0.526266  0.728718  1.190324  ...     -0.209234          -0.615200                         -0.292156
2         -0.526266 -0.073248  0.503752  ...     -0.209234           1.625488                         -0.292156
3          1.900181  0.728718  1.190324  ...     -0.209234          -0.615200                         -0.292156
4         -0.526266 -0.073248 -0.182821  ...     -0.209234          -0.615200                         -0.292156
...             ...       ...       ...  ...           ...                ...                               ...
3619      -0.526266 -0.073248 -0.182821  ...     -0.209234          -0.615200                         -0.292156
3620      -0.526266 -0.073248 -0.182821  ...     -0.209234          -0.615200                         -0.292156
3621      -0.526266  0.728718  0.503752  ...     -0.209234          -0.615200                         -0.292156
3622      -0.526266 -0.875214 -1.555965  ...     -0.209234          -0.615200                         -0.292156
3623      -0.526266 -0.875214 -0.869393  ...     -0.209234          -0.615200                         -0.292156

[3624 rows x 104 columns]

In [91]:
kfold = KFold(n_splits=10, shuffle=True, random_state=42)
scores = cross_val_score(LinearRegression(), X_scaled, y_log, cv=kfold, scoring='r2')

In [92]:
scores.mean(),scores.std()

(np.float64(0.8412545275240835), np.float64(0.022407727071017423))

In [93]:
lr = LinearRegression()
ridge = Ridge(alpha=0.0001)

In [94]:
lr.fit(X_scaled,y_log)

LinearRegression()

In [99]:
lr.coef_

array([ 0.11279299,  0.05854052,  0.06068365,  0.22080779,  0.05588357,
       -0.00452731,  0.01176143,  0.01453063,  0.06287553,  0.02023244,
        0.03043628, -0.00245028,  0.0211045 ,  0.01521788,  0.04345817,
        0.0566441 ,  0.00539546,  0.02532403,  0.03116244,  0.04653087,
        0.05437416,  0.00485652, -0.00208371,  0.04204238,  0.02138374,
        0.03000331,  0.02467778,  0.00197409,  0.05223129,  0.03953169,
        0.0385562 ,  0.08017538,  0.09772959,  0.0124076 ,  0.06611888,
        0.00618347,  0.01467271,  0.03465113,  0.05520514,  0.02018261,
        0.03134026,  0.02474229,  0.01551209,  0.00665694,  0.02221255,
        0.02920692,  0.01582799,  0.07510043,  0.03731337,  0.02899267,
        0.02801179,  0.07226738,  0.05784098,  0.00439208,  0.09893836,
        0.0061648 ,  0.01839796,  0.0789873 ,  0.06377814,  0.02518367,
        0.03812816,  0.0437217 ,  0.03272503,  0.03346204, -0.00223223,
        0.03690147,  0.05933023,  0.05615406,  0.05917906,  0.10127768,
        0.07453551,  0.06752974,  0.0309305 ,  0.0522877 ,  0.01626825,
        0.05177159,  0.01572959,  0.04794508,  0.00473987,  0.0370692 ,
        0.01427446,  0.01939904,  0.01006127,  0.04174155, -0.00226062,
        0.00796687,  0.04965392,  0.03393982,  0.02800436,  0.01500877,
        0.04498855,  0.02458342,  0.02619401,  0.03015163,  0.00453327,
        0.0199586 ,  0.01476447,  0.0074859 ,  0.00740292,  0.00245536,
        0.01314078,  0.0171641 , -0.00811924,  0.01590997])

In [95]:
ridge.fit(X_scaled,y_log)

Ridge(alpha=0.0001)

In [100]:
ridge.coef_

array([ 0.11279299,  0.05854052,  0.06068365,  0.22080778,  0.05588356,
       -0.00452731,  0.01176144,  0.01453059,  0.06287537,  0.02023234,
        0.03043615, -0.00245035,  0.02110441,  0.01521776,  0.04345806,
        0.05664396,  0.00539541,  0.02532396,  0.03116236,  0.0465308 ,
        0.05437406,  0.00485644, -0.00208374,  0.04204231,  0.02138369,
        0.03000327,  0.02467771,  0.00197404,  0.05223122,  0.03953157,
        0.03855613,  0.08017529,  0.0977295 ,  0.01240758,  0.06611879,
        0.00618341,  0.01467268,  0.03465109,  0.05520502,  0.02018254,
        0.0313401 ,  0.02474225,  0.01551204,  0.00665684,  0.02221251,
        0.02920687,  0.01582797,  0.07510033,  0.03731332,  0.02899262,
        0.02801173,  0.07226726,  0.05784088,  0.004392  ,  0.09893825,
        0.00616476,  0.01839791,  0.07898723,  0.06377806,  0.02518362,
        0.03812805,  0.04372163,  0.03272499,  0.033462  , -0.00223228,
        0.03690141,  0.05933014,  0.056154  ,  0.05917898,  0.10127754,
        0.07453541,  0.06752961,  0.03093041,  0.05228756,  0.01626816,
        0.05177144,  0.01572952,  0.047945  ,  0.00473985,  0.03706913,
        0.01427441,  0.01939897,  0.01006121,  0.04174142, -0.00226066,
        0.00796684,  0.04965378,  0.0339397 ,  0.02800424,  0.01500867,
        0.04498839,  0.02458331,  0.02619394,  0.03015152,  0.0045332 ,
        0.01995846,  0.01476441,  0.00748575,  0.00740287,  0.00245525,
        0.01314068,  0.01716392, -0.00811926,  0.01590997])

In [101]:
coef_df = pd.DataFrame(lr.coef_.reshape(1,104),columns=X.columns).stack().reset_index().drop(columns=['level_0']).rename(columns={'level_1':'feature',0:'coef'})

In [102]:
coef_df

                              feature      coef
0                       property_type  0.112793
1                             bedRoom  0.058541
2                            bathroom  0.060684
3                       built_up_area  0.220808
4                        servant room  0.055884
..                                ...       ...
99                   sector_sector 95  0.002455
100                  sector_sector 99  0.013141
101                      sector_sohna  0.017164
102                 agePossession_old -0.008119
103  agePossession_under construction  0.015910

[104 rows x 2 columns]

In [103]:
# 1. Import necessary libraries
import statsmodels.api as sm

# 2. Add a constant to X
X_with_const = sm.add_constant(X_scaled)

# 3. Fit the model
model = sm.OLS(y_log, X_with_const).fit()

# 4. Obtain summary statistics
print(model.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                  price   R-squared:                       0.855
Model:                            OLS   Adj. R-squared:                  0.850
Method:                 Least Squares   F-statistic:                     198.9
Date:                Tue, 21 Jul 2026   Prob (F-statistic):               0.00
Time:                        02:19:23   Log-Likelihood:                 460.85
No. Observations:                3624   AIC:                            -711.7
Df Residuals:                    3519   BIC:                            -61.19
Df Model:                         104
Covariance Type:            nonrobust
====================================================================================================
                                       coef    std err          t      P>|t|      [0.025      0.975]
----------------------------------------------------------------------------------------------------
const                                1.0454      0.004    291.037      0.000       1.038       1.052
property_type                        0.1128      0.005     21.308      0.000       0.102       0.123
bedRoom                              0.0585      0.007      8.810      0.000       0.046       0.072
bathroom                             0.0607      0.007      8.853      0.000       0.047       0.074
built_up_area                        0.2208      0.005     43.037      0.000       0.211       0.231
servant room                         0.0559      0.005     12.142      0.000       0.047       0.065
furnishing_type                     -0.0045      0.004     -1.174      0.240      -0.012       0.003
luxury_category                      0.0118      0.004      2.868      0.004       0.004       0.020
sector_sector 10                     0.0145      0.004      3.670      0.000       0.007       0.022
sector_sector 102                    0.0629      0.007      8.597      0.000       0.049       0.077
sector_sector 103                    0.0202      0.005      3.828      0.000       0.010       0.031
sector_sector 104                    0.0304      0.006      5.031      0.000       0.019       0.042
sector_sector 105                   -0.0025      0.005     -0.535      0.592      -0.011       0.007
sector_sector 106                    0.0211      0.005      4.035      0.000       0.011       0.031
sector_sector 107                    0.0152      0.006      2.606      0.009       0.004       0.027
sector_sector 108                    0.0435      0.006      7.510      0.000       0.032       0.055
sector_sector 109                    0.0566      0.007      8.617      0.000       0.044       0.070
sector_sector 11                     0.0054      0.004      1.271      0.204      -0.003       0.014
sector_sector 110                    0.0253      0.005      5.436      0.000       0.016       0.034
sector_sector 111                    0.0312      0.005      6.735      0.000       0.022       0.040
sector_sector 112                    0.0465      0.005     10.037      0.000       0.037       0.056
sector_sector 113                    0.0544      0.005     10.191      0.000       0.044       0.065
sector_sector 12                     0.0049      0.005      0.978      0.328      -0.005       0.015
sector_sector 13                    -0.0021      0.004     -0.541      0.588      -0.010       0.005
sector_sector 14                     0.0420      0.005      9.324      0.000       0.033       0.051
sector_sector 15                     0.0214      0.004      5.276      0.000       0.013       0.029
sector_sector 17                     0.0300      0.004      7.429      0.000       0.022       0.038
sector_sector 2                      0.0247      0.005      5.471      0.000       0.016       0.034
sector_sector 21                     0.0020      0.004      0.493      0.622      -0.006       0.010
sector_sector 22                     0.0522      0.004     11.681      0.000       0.043       0.061
sector_sector 23                     0.0395      0.006      6.476      0.000       0.028       0.052
sector_sector 24                     0.0386      0.005      8.324      0.000       0.029       0.048
sector_sector 25                     0.0802      0.005     15.463      0.000       0.070       0.090
sector_sector 26                     0.0977      0.005     18.416      0.000       0.087       0.108
sector_sector 27                     0.0124      0.004      3.341      0.001       0.005       0.020
sector_sector 28                     0.0661      0.005     13.075      0.000       0.056       0.076
sector_sector 3                      0.0062      0.004      1.403      0.161      -0.002       0.015
sector_sector 30                     0.0147      0.004      3.836      0.000       0.007       0.022
sector_sector 31                     0.0347      0.004      8.531      0.000       0.027       0.043
sector_sector 33                     0.0552      0.006      9.040      0.000       0.043       0.067
sector_sector 36                     0.0202      0.005      4.410      0.000       0.011       0.029
sector_sector 37                     0.0313      0.007      4.247      0.000       0.017       0.046
sector_sector 38                     0.0247      0.004      6.035      0.000       0.017       0.033
sector_sector 39                     0.0155      0.004      3.793      0.000       0.007       0.024
sector_sector 4                      0.0067      0.005      1.222      0.222      -0.004       0.017
sector_sector 40                     0.0222      0.004      5.698      0.000       0.015       0.030
sector_sector 41                     0.0292      0.004      7.095      0.000       0.021       0.037
sector_sector 42                     0.0158      0.004      4.235      0.000       0.008       0.023
sector_sector 43                     0.0751      0.005     13.839      0.000       0.064       0.086
sector_sector 45                     0.0373      0.004      9.293      0.000       0.029       0.045
sector_sector 46                     0.0290      0.004      6.964      0.000       0.021       0.037
sector_sector 47                     0.0280      0.004      6.504      0.000       0.020       0.036
sector_sector 48                     0.0723      0.006     11.934      0.000       0.060       0.084
sector_sector 49                     0.0578      0.005     10.715      0.000       0.047       0.068
sector_sector 5                      0.0044      0.005      0.878      0.380      -0.005       0.014
sector_sector 50                     0.0989      0.006     16.839      0.000       0.087       0.110
sector_sector 51                     0.0062      0.004      1.539      0.124      -0.002       0.014
sector_sector 52                     0.0184      0.004      4.376      0.000       0.010       0.027
sector_sector 53                     0.0790      0.005     16.778      0.000       0.070       0.088
sector_sector 54                     0.0638      0.005     13.682      0.000       0.055       0.073
sector_sector 55                     0.0252      0.004      6.185      0.000       0.017       0.033
sector_sector 56                     0.0381      0.006      6.706      0.000       0.027       0.049
sector_sector 57                     0.0437      0.005      9.308      0.000       0.035       0.053
sector_sector 58                     0.0327      0.004      8.149      0.000       0.025       0.041
sector_sector 59                     0.0335      0.004      8.224      0.000       0.025       0.041
sector_sector 6                     -0.0022      0.004     -0.542      0.588      -0.010       0.006
sector_sector 60                     0.0369      0.004      8.585      0.000       0.028       0.045
sector_sector 61                     0.0593      0.005     11.216      0.000       0.049       0.070
sector_sector 62                     0.0562      0.004     12.977      0.000       0.048       0.065
sector_sector 63                     0.0592      0.005     12.127      0.000       0.050       0.069
sector_sector 65                     0.1013      0.007     15.285      0.000       0.088       0.114
sector_sector 66                     0.0745      0.005     14.129      0.000       0.064       0.085
sector_sector 67                     0.0675      0.006     11.106      0.000       0.056       0.079
sector_sector 68                     0.0309      0.005      6.342      0.000       0.021       0.040
sector_sector 69                     0.0523      0.007      7.652      0.000       0.039       0.066
sector_sector 7                      0.0163      0.005      3.172      0.002       0.006       0.026
sector_sector 70                     0.0518      0.007      7.431      0.000       0.038       0.065
sector_sector 71                     0.0157      0.005      3.340      0.001       0.006       0.025
sector_sector 72                     0.0479      0.005      9.959      0.000       0.039       0.057
sector_sector 73                     0.0047      0.004      1.264      0.206      -0.003       0.012
sector_sector 74                     0.0371      0.004      8.367      0.000       0.028       0.046
sector_sector 76                     0.0143      0.004      3.311      0.001       0.006       0.023
sector_sector 77                     0.0194      0.005      4.075      0.000       0.010       0.029
sector_sector 78                     0.0101      0.004      2.350      0.019       0.002       0.018
sector_sector 79                     0.0417      0.006      6.464      0.000       0.029       0.054
sector_sector 8                     -0.0023      0.004     -0.572      0.568      -0.010       0.005
sector_sector 80                     0.0080      0.004      2.084      0.037       0.000       0.015
sector_sector 81                     0.0497      0.007      7.543      0.000       0.037       0.063
sector_sector 82                     0.0339      0.006      5.818      0.000       0.023       0.045
sector_sector 83                     0.0280      0.006      4.601      0.000       0.016       0.040
sector_sector 84                     0.0150      0.006      2.719      0.007       0.004       0.026
sector_sector 85                     0.0450      0.007      6.318      0.000       0.031       0.059
sector_sector 86                     0.0246      0.006      4.184      0.000       0.013       0.036
sector_sector 88                     0.0262      0.005      5.584      0.000       0.017       0.035
sector_sector 89                     0.0302      0.006      5.189      0.000       0.019       0.042
sector_sector 9                      0.0045      0.005      0.988      0.323      -0.004       0.014
sector_sector 90                     0.0200      0.007      3.019      0.003       0.007       0.033
sector_sector 91                     0.0148      0.004      3.405      0.001       0.006       0.023
sector_sector 92                     0.0075      0.007      1.086      0.278      -0.006       0.021
sector_sector 93                     0.0074      0.004      1.839      0.066      -0.000       0.015
sector_sector 95                     0.0025      0.006      0.425      0.671      -0.009       0.014
sector_sector 99                     0.0131      0.005      2.486      0.013       0.003       0.024
sector_sohna                         0.0172      0.008      2.103      0.036       0.001       0.033
agePossession_old                   -0.0081      0.005     -1.596      0.111      -0.018       0.002
agePossession_under construction     0.0159      0.004      3.882      0.000       0.008       0.024
==============================================================================
Omnibus:                      543.578   Durbin-Watson:                   1.926
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             4407.792
Skew:                          -0.465   Prob(JB):                         0.00
Kurtosis:                       8.322   Cond. No.                         18.6
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [104]:
y_log.std()

0.558894978881325

In [105]:
X_scaled['bedRoom'].std()

1.0001379976547116

In [106]:
0.21 * (0.557/1)

0.11697

In [107]:
np.expm1(0.030)

np.float64(0.030454533953516858)